### ISSUE TITLE
cathub isn't cross platform

### ISSUE THREAD

**Issue by brookskindle** [brookskindle/cathub#5]
It appears to be written for a unix platform, which makes it an issue for anyone running windows or (mac?). Can we re-write our code to be cross platform?

**Comment by lancekindle** [comment]
My current implementation does away with the bash script that symlinks our githooks into .git/hooks.
However, I don't think it truly solves our problem since it still uses pre-made symlinks, which may not work on other platforms.

I think our only valid fix is to copy the .githooks files into .git/hooks/ entirely, rather than linking them.

**Comment by brookskindle** [comment]
Hmm yeah there doesn't seem to be a good cross-platform way of performing symlinks. We'd have to detect the OS and call an appropriate script based on that,  I think
